### ISSUE TITLE
Add change endpoint option

### ISSUE THREAD

**Issue by Nir-Tal** [bakins/php-fpm-exporter#22]
Hi, first thanks for the exporter. It's exactly what I was looking for!!

I'm using a single port to publish the data with different endpoints. 
Any chance you add `--web.telemetry-path="/metrics"` same as implemented in the node exporter? 
That would be great.
Thanks and continue the good work.

**Comment by bakins** [comment]
@Nir-Tal this sound relatively straight forward. I can do this when I get a bit of free time. Thanks for the suggestion!

**Comment by Nir-Tal** [comment]
@bakins thanks!!! please ping me if you got to do it 😀
