### ISSUE TITLE
Consider including the pool in the lables

### ISSUE THREAD

**Issue by andrewhowdencom** [bakins/php-fpm-exporter#3]
In theory, you can run different PHP pools. I'm not too sure how this is rendered in the status page (I would imagine that there'd be one page per pool); additionally, the daemon doesn't have to support multiple (the daemon could simply be run multiple times on different ports or reverse proxied).

So, the metrics would be 

```
phpfpm_listen_queue_length_connections{pool="www"} = 38
```

**Comment by bakins** [comment]
php-fpm assumes one pool per listening socket. At $DAYJOB, we just run separate instances rather than using pools. Each php-fpm instance gets its own php-fpm-exporter.

**Comment by andrewhowdencom** [comment]
Yah I've only seen separate pools on one (particularly insane) environment. Happy closing this.
