### ISSUE TITLE
Consider updating the process metrics to use labels to express their state

### ISSUE THREAD

**Issue by andrewhowdencom** [bakins/php-fpm-exporter#4]
Currently there are these two metrics:

```
# HELP phpfpm_active_processes Active process count
# TYPE phpfpm_active_processes gauge
phpfpm_active_processes 1
# HELP phpfpm_idle_processes Idle process count
# TYPE phpfpm_idle_processes gauge
```

Arguably, they are showing the same thing - but expressing different characteristics. Prometheus docs indicate that this should be expressed using labels. 

Additionally, the third metric:

```
# HELP phpfpm_total_processes Total process count
# TYPE phpfpm_total_processes gauge
phpfpm_total_processes 3
```

can be derived from the first two in prometheus / as part of a rule, rather than expressed by the exporter itself. I thus think it could be dropped; instead, replaced with docs indicating how this can be done as a rule or query, as well as some note as to why this is done.

This is kind of two issues rolled into one, but they're about the same metrics, so it feels like a reasonable way to start the discussion.

**Comment by bakins** [comment]
So metric may look something like:

```
php_processes_total{state="idle"} 1
php_processes_total{state="active"} 2
```

**Comment by andrewhowdencom** [comment]
exactly!

**Comment by bakins** [comment]
@andrewhowdencom see #5 - code isn't great, but it works.

**Comment by andrewhowdencom** [comment]
That looks awesome! Also I didn't know how to do it so it's cool seeing you do it lol.

**Comment by bakins** [comment]
Merged the PR, so closing this.
