### ISSUE TITLE
Signed releases

### ISSUE THREAD

**Issue by atmosx** [bakins/php-fpm-exporter#6]
Hi!

First thanks for the exporter!

We're planning on using it in our production servers and I'd love to automate the installation.

Is it possible to introduce signed (SHA256) binary releases?

Thanks!

**Comment by bakins** [comment]
Do you just want me to include a text file with the SHA256 of the binaries?

**Comment by atmosx** [comment]
Yes

**Comment by bakins** [comment]
https://github.com/bakins/php-fpm-exporter/releases/tag/v0.3.3 has sha256 sums for the binaries.
