### ISSUE TITLE
Updating the quay docker container?

### ISSUE THREAD

**Issue by mikn** [bakins/php-fpm-exporter#8]
Hi!
Thank you for this project! We plan on using this collector as a container in a kubernetes deployment. Is it possible for you to update the quay.io image with the latest version? Maybe even set up automated builds. :)

**Comment by bakins** [comment]
@mikn apologies for the belated reply.  I need to setup automated builds for this project. I'll update the quay.io one in the meantime.

**Comment by insekticid** [comment]
gogogo, fire in the hole! 
we are waiting!

**Comment by bakins** [comment]
Available at quay.io/bakins/php-fpm-exporter:v0.4.0
